version: 0.2
env:
  parameter-store:
     DOCKER_REGISTRY_USERNAME: /pythonapp/docker_username
     DOCKER_REGISTRY_PASSWORD: /pythonapp/docker_password
     DOCKER_REGISTRY_URL: /pythonapp/docker_url
     # key: "value"
phases:
  install:
    #If you use the Ubuntu standard image 2.0 or later, you must specify runtime-versions.
    #If you specify runtime-versions and use an image other than Ubuntu standard image 2.0, the build fails.
    runtime-versions:
       python: 3.11
  pre_build:
    commands:
       pip install -r python-app/requirements.txt
  build:
    commands:
       - cd python-app
       - echo "building docker image"
       - echo "logging in to DockerHub.."
       - echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USERNAME" --password-stdin
       - docker build -t "$DOCKER_REGISTRY_USERNAME/python-app:latest" .
       - docker push "$DOCKER_REGISTRY_USERNAME/python-app:latest"
  post_build:
    commands:
       - echo "build is successfull"
